class AssetData{
  static String logo="assets/images/img.png";
  static List activites=["assets/images/img_2.png","assets/images/img_3.png","assets/images/img_4.png"];
  static const kBackGround = 'assets/images/auth.png';
  static List services=['assets/images/services/img.png','assets/images/services/img_1.png','assets/images/services/img_2.png','assets/images/services/img_3.png','assets/images/services/img_4.png','assets/images/services/img_5.png'];
  static List restaurants=['assets/images/img_6.png','assets/images/img_7.png','assets/images/img_6.png','assets/images/img_7.png'];
  static List gallery=[
    "assets/images/gallery/img.png",
    " assets/images/gallery/img_1.png",
    "assets/images/gallery/img_2.png",
    "assets/images/gallery/img_3.png",
   " assets/images/gallery/img_4.png",
    "assets/images/gallery/img_5.png",
        "assets/images/gallery/IMG_5809.jpg",
"    assets/images/gallery/IMG_6323.jpg",
"    assets/images/gallery/IMG_6451.jpg",
"    assets/images/gallery/IMG_6460.jpg",
"    assets/images/gallery/IMG_6464.jpg",
"    assets/images/gallery/IMG_6468.jpg",
    "assets/images/gallery/IMG_6469.jpg",
    "assets/images/gallery/IMG_6472.jpg",
    "assets/images/gallery/IMG_6479.jpg",
    "assets/images/gallery/IMG_6487.jpg",
    "assets/images/gallery/IMG_6490.jpg",
    "assets/images/gallery/IMG_6497.jpg",
    "assets/images/gallery/IMG_6508.jpg",
    "assets/images/gallery/IMG_6512.jpg",
    "assets/images/gallery/IMG_6513.jpg",
    "assets/images/gallery/IMG_6514.jpg",
    "assets/images/gallery/IMG_6516.jpg",
    "assets/images/gallery/IMG_6517.jpg",
    "assets/images/gallery/IMG_6519.jpg",
    "assets/images/gallery/IMG_6520.jpg",
    "assets/images/gallery/IMG_6521.jpg",
    "assets/images/gallery/IMG_6522.jpg",
    "assets/images/gallery/IMG_6523.jpg",
    "assets/images/gallery/IMG_6531.jpg",
    "assets/images/gallery/IMG_6532.jpg",
    "assets/images/gallery/IMG_6533.jpg",
    "assets/images/gallery/IMG_6534.jpg",
    "assets/images/gallery/IMG_6535.jpg",
    "assets/images/gallery/IMG_6536.jpg",
    "assets/images/gallery/IMG_6544.jpg",
    "assets/images/gallery/IMG_6552.jpg",
    "assets/images/gallery/IMG_6553.jpg",
    "assets/images/gallery/IMG_6592.jpg",
    "assets/images/gallery/IMG_6613.jpg",
    "assets/images/gallery/IMG_7175.jpg",
    "assets/images/gallery/IMG_7200.jpg",
    "assets/images/gallery/IMG_7202.jpg",
    "assets/images/gallery/IMG_7207.jpg",
    "assets/images/gallery/IMG_7253.jpg",
    "assets/images/gallery/IMG_7282.jpg",
    "assets/images/gallery/IMG_7300.jpg",
    "assets/images/gallery/IMG_7301.jpg",
    "assets/images/gallery/IMG_9661.jpg",
    "assets/images/gallery/IMG_9685.jpg",
    "assets/images/gallery/IMG_9728.jpg",
    "assets/images/gallery/IMG_9737.jpg",
    "assets/images/gallery/IMG_9743.jpg",
    "assets/images/gallery/IMG_9745.jpg",
    "assets/images/gallery/IMG_9774.jpg",
    "assets/images/gallery/IMG_9883.jpg",
    "assets/images/gallery/IMG_9902.jpg",
  ];
}